version: "3.7"

services:
  simulator:
    build:
      context: .
    container_name: simulator
    ports:
      - "8444:8444"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "sh", "-c" ,"apk --no-cache add curl", ";", "curl", "http://localhost:8444/health"]
      timeout: 20s
      retries: 10
      interval: 30s
